version: '3'
services:
  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    restart: 'always'
  todofront:
    restart: 'always'
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
  todotests:
    build: ./todo-app/tests
    restart: 'always'
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
